"""
Django settings for shop_vivu project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-((+i5dou_=nhkyw9&n5$$nzn_edz%m$n&s7!qknp3=ncvavs!b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

BASE_URL = "http://127.0.0.1:8000"

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'chartjs',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    "products",
    'cart',
    'user',
    'import_export',
    'django_filters',
    'django_celery_beat',
    'recommendation',
]
AUTH_USER_MODEL = 'user.User'

VNPAY_MERCHANT_CODE = "68S4KYOT"  # Lấy từ VNPAY
VNPAY_HASH_SECRET = "EHO3H7BJKKBSBSAUVBC77FQM1BG5DAV3"  # Lấy từ VNPAY
VNPAY_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"  # URL của VNPAY (sandbox cho test)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5173',  # Cho phép frontend từ localhost:5173
]

ROOT_URLCONF = 'shop_vivu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop_vivu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'alomy',  # Tên cơ sở dữ liệu bạn đã tạo
        'USER': 'root',  # Tên người dùng MySQL
        'PASSWORD': '123456',  # Mật khẩu người dùng MySQL
        'HOST': 'localhost',  # Địa chỉ máy chủ (localhost nếu chạy trên máy cục bộ)
        'PORT': '3306',  # Cổng MySQL (mặc định là 3306)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'vi'


TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
import os
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'# Đường dẫn URL để truy cập các tệp media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')# Đường dẫn trên hệ thống để lưu các tệp media

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Thêm dòng này để sử dụng Token
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Chỉ cho phép những người dùng đã xác thực
    ],
}

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Cấu hình Redis cho Celery
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'train-model-every-week': {
        'task': 'recommendation.tasks.train_recommendation_model',
        'schedule': crontab(hour=0, minute=0, day_of_week='sunday'),  # Lên lịch vào mỗi chủ nhật lúc 00:00
    },
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

JAZZMIN_SETTINGS = {
    "site_title": "VIVU Admin",
    "site_header": "VIVU Shop",
    "site_brand": "VIVU Shop",
    "welcome_sign": "Chào mừng đến với trang quản trị",
    "site_logo": "logo.png",
    "login_logo": "logo.png",
    "copyright": "VIVU Shop",
    "icons": {
        "auth": "fas fa-users-cog",
        "user.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "cart.Order": "fa-solid fa-cart-shopping",
        "cart.OrderLine": "fa-solid fa-cart-shopping",
        "products.Product": "fa-solid fa-shirt",
        "products.Banner": "fa-solid fa-shirt",
        "products.Category": "fa-solid fa-shirt",
        "products.Image": "fa-solid fa-shirt",
        "products.StockQuantity": "fa-solid fa-shirt",
        "products.PurchaseInvoiceLine": "fa-solid fa-shirt",
        "products.PurchaseInvoice": "fa-solid fa-shirt",
        "products.Review": "fa-solid fa-shirt",
        "products.Color": "fa-solid fa-shirt",
        "products.Size": "fa-solid fa-shirt",
        

    },
    
    "topmenu_links": [
        {"app": "products"},
        {"app": "cart"},
        {"app": "user"},
        {"name": "Thống kê doanh thu", "url": "/api/dashboard/", "icon": "fa fa-line-chart"},
    ],
    "show_ui_builder": True,
    "custom_css": "common/css/main.css",  
    "custom_js": "common/js/main.js",    
}

