# Generated by Django 5.1.4 on 2024-12-16 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_initial"),
        ("products", "0003_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orderline",
            name="color",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="products.color",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="size",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                to="products.size",
            ),
        ),
    ]
